# Generated by Django 4.0.6 on 2022-07-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
        ('store', '0013_alter_customer_options'),
        ('store', '0015_alter_productimage_image'),
    ]

    operations = [
    ]
